name: seamus
favicon: null
layout_spectrum: 0.3662956713233143
typography_spectrum: 0.33672523219138384
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5
  lightness: 0.18718292168341577
  saturation: 0.8709049602039158
  rhythmicContrast: 0.2952901248354465
purpose: []
